# Generated by Django 4.0 on 2022-05-04 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='کد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='از زمان :')),
                ('valid_to', models.DateTimeField(verbose_name='تا زمان :')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='مقدار تخفیف')),
                ('active', models.BooleanField(verbose_name='فعال بودن کد')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن ها',
            },
        ),
    ]
