# Generated by Django 3.2 on 2022-02-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupons_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'کوپن', 'verbose_name_plural': 'کوپن ها'},
        ),
    ]
