# Generated by Django 4.0 on 2022-04-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='تصویر اصلی محصول')),
                ('image2', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='تصویر جانبی 1 محصول')),
                ('image3', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='تصویر جانبی 2 محصول')),
                ('image4', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='تصویر جانبی 3 محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('status', models.CharField(choices=[('u', 'ناموجود'), ('a', 'موجود'), ('c', 'قابل سفارش')], max_length=1, verbose_name='وضعیت')),
                ('pishnahad', models.BooleanField(default=False, verbose_name='پیشنهاد شده')),
                ('Inventory', models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام ویژگی')),
                ('value', models.CharField(max_length=256, verbose_name='مقدار ویژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triat', to='shop.product')),
            ],
        ),
    ]
