# Generated by Django 3.2 on 2022-02-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pishnahad',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت محصول'),
        ),
    ]
