# Generated by Django 3.2 on 2022-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220216_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=1, upload_to='products/%Y/%m/%d', verbose_name='تصویر جانبی 1 محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=1, upload_to='products/%Y/%m/%d', verbose_name='تصویر جانبی 2 محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default=1, upload_to='products/%Y/%m/%d', verbose_name='تصویر جانبی 3 محصول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='تصویر اصلی محصول'),
        ),
    ]
