# Generated by Django 4.0 on 2022-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220228_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Inventory',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
