# Generated by Django 4.0 on 2022-04-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_inventory_alter_product_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام ویژگی')),
                ('value', models.CharField(max_length=256, verbose_name='مقدار ویژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triat', to='shop.product')),
            ],
        ),
    ]
