# Generated by Django 4.0 on 2022-04-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_alter_blockeduser_id_alter_blockeduserhistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
