# Generated by Django 3.2 on 2022-02-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updeated',
            new_name='updated',
        ),
    ]
