# Generated by Django 3.2 on 2022-02-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('kho', 'خراسان'), ('teh', 'تهران'), ('esf', 'اصفهان')], max_length=100),
        ),
    ]
