# Generated by Django 3.2 on 2022-03-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('خراسان', 'خراسان'), ('تهران', 'تهران'), ('اصفهان', 'اصفهان')], max_length=100),
        ),
    ]
